### ISSUE TITLE
Postfix via supervisor exits

### ISSUE THREAD

**Issue by sydekumf** [techdivision/dnmp-debian#2]
The postfix command via supervisor exits. If you run the command which gets executed via supervisor, it says, that postfix is already running:
```
/usr/sbin/postfix -c /etc/postfix start
postfix/postfix-script: fatal: the Postfix mail system is already running
```

If you do `ps aux` you see it is already there. Seems to be running by the OS? Maybe the supervisor configuration for postfix is obsolete then?

**Comment by zelgerj** [comment]
Thanks for this, but it's intentional behavior. The supervisord configuration is used to start the postfix process with it's wrapper script ```/usr/sbin/postfix``` initially. Unfortunately, postfix can not be started as an open process.
